version: "3"

services:
  postgres-utc:
    image: postgres:15
    container_name: postgres-utc
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: timezone_test
      TZ: UTC
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d

  postgres-jst:
    image: postgres:15
    container_name: postgres-jst
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: timezone_test
      TZ: Asia/Tokyo
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d

  postgres-est:
    image: postgres:15
    container_name: postgres-est
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: timezone_test
      TZ: America/New_York
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5434:5432"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
